var ARENANET_DEVELOPERS = [
  "Mike-OBrien-ArenaNet",
  "brin5tar",
  "ArenaNetSupportTeam",
  "chris_lye_arenanet",
  "maclaine",
  "cameronjdunn",
  "Tivac",
  "Kuraine",
  "PrinceSuperfly",
  "ChrisCleary",
  "ArenaColin",
  "ArenaNetRyanD",
  "IsaiahCartwright",
  "Anet_Sean",
  "Anet_Tirzah",
  "adamblaen",
  "ArenaNetMike",
  "codonomicus",
  "anet_samuel",
  "ArenaNetAnthony",
  "Merryeli",
  "ANetJohan",
  "GM_Awesomeness",
  "GaileGray",
  "DevonCarver",
  "Joshua_Davis",
  "ProbablyJohnSmith",
  "ArenaKeenan",
  "Anet_Hugh",
  "SnowcrashCTW",
  "lancehit_anet",
  "mikezadorojny",
  "DrStephenCW",
  "ArenaNetEvanL",
  "ProHeals",
  "LinseyMurdock",
  "ArenaNetBG",
  "Alexander-Youngblood",
  "Anet_Goremond",
  "BobbyStein",
  "GMGus",
  "ANET_Faerla",
];

var REDDIT_API_URL = "https://www.reddit.com/";

var SUBREDDIT_NAME = "Guildwars2";
